<?php
$this->title = "My Albums";
$this->headTitle($this->title);

?>
<div id="show" >
    <p>Albums</p>
<table id="table_Album"  class="table table-striped table-bordered container-fluid ">
   <thead>
    <tr>
        <th>id</th>
        <th>Artist_id</th>
        <th>Artist_Name</th>
        <th>Title</th>
        <th>options</th>
    </tr>
   </thead>


</table>
</div>
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <strong>Add Albums</strong>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color:#eee;">
            <div class="form-group row">
      </div>

            </div>

            <div class="modal-footer " >
                    <button type="button"  id="submit_addalbum"  class="btn btn-primary">Add Album</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>


            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
             <strong> Edit Albums</strong>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color:#eee;">
                <div class="form-group row">
                </div>

            </div>

            <div class="modal-footer ">
                <button type="button"  id="submit_editalbum"  class="btn btn-primary">edit Album</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>


            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
              <strong> delete Albums</strong>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color:#eee;">
                <div class="form-group row">
                </div>
            </div>

            <div class="modal-footer ">
                <button type="button"  id="Delete_album"  class="btn btn-primary">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>


            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="add_artistModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <strong> Add Artist </strong>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color:#eee;">
                <div class="form-group">
                </div>
            </div>

            <div class="modal-footer">

                <button type="button"  id="submit_add_artist"  class="btn btn-primary">Add Artist</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>


            </div>
        </div>
    </div>
</div>